export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CHANGE_HEADER_COLOR = 'CHANGE_HEADER_COLOR';
export const SHOW_HEADER_DROP_DOWN = 'SHOW_HEADER_DROP_DOWN';
export const HIDE_HEADER_DROP_DOWN = 'HIDE_HEADER_DROP_DOWN';
export const CHANGE_TITLE_MARGIN = 'CHANGE_TITLE_MARGIN';
